# max_width = 60
# use_small_heuristics = "Max"
# format_generated_files = false

reorder_imports = true
# currently unsupported but want them in when stable
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
